USE [master]
GO

/****** Object:  Database [LostandFound]    Script Date: 2018/12/7 9:56:35 ******/
CREATE DATABASE [LostandFound]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LostandFound', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\LostandFound.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LostandFound_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\LostandFound_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [LostandFound] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LostandFound].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LostandFound] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LostandFound] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LostandFound] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LostandFound] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LostandFound] SET ARITHABORT OFF 
GO

ALTER DATABASE [LostandFound] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LostandFound] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LostandFound] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LostandFound] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LostandFound] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LostandFound] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LostandFound] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LostandFound] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LostandFound] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LostandFound] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LostandFound] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LostandFound] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LostandFound] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LostandFound] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LostandFound] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LostandFound] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LostandFound] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LostandFound] SET RECOVERY FULL 
GO

ALTER DATABASE [LostandFound] SET  MULTI_USER 
GO

ALTER DATABASE [LostandFound] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LostandFound] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LostandFound] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LostandFound] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LostandFound] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LostandFound] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LostandFound] SET  READ_WRITE 
GO

